# Generated by Django 6.1 on 2026-08-26 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asignacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('porcentaje', models.DecimalField(decimal_places=2, max_digits=5)),
                ('fecha_asignacion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Bien',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('descripcion', models.TextField(blank=True)),
                ('tipo', models.CharField(choices=[('DINERO', 'Dinero'), ('ARCHIVO', 'Archivo'), ('IMAGEN', 'Imagen'), ('CONTRASENA', 'Contrasenia'), ('DOCUMENTO', 'Documento'), ('BITCOIN', 'Bitcoin'), ('OTRO', 'Otro')], default='OTRO', max_length=12)),
                ('valor', models.DecimalField(decimal_places=8, default=0, max_digits=18)),
                ('archivo', models.FileField(blank=True, null=True, upload_to='bienes/')),
                ('estado', models.CharField(choices=[('BLOQUEADO', 'Bloqueado'), ('TRANSFERIDO', 'Transferido')], default='BLOQUEADO', max_length=12)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_transferencia', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
