# Generated by Django 6.1 on 2026-09-16 00:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bien',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('descripcion', models.TextField(blank=True)),
                ('tipo', models.CharField(choices=[('DINERO', 'Dinero'), ('ARCHIVO', 'Archivo'), ('IMAGEN', 'Imagen'), ('CONTRASENA', 'Contrasenia'), ('DOCUMENTO', 'Documento'), ('BITCOIN', 'Bitcoin'), ('OTRO', 'Otro')], default='OTRO', max_length=12)),
                ('valor', models.DecimalField(decimal_places=8, default=0, max_digits=18)),
                ('archivo', models.FileField(blank=True, null=True, upload_to='bienes/')),
                ('estado', models.CharField(choices=[('BLOQUEADO', 'Bloqueado'), ('TRANSFERIDO', 'Transferido')], default='BLOQUEADO', max_length=12)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_transferencia', models.DateTimeField(blank=True, null=True)),
                ('propietario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bienes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Asignacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('porcentaje', models.DecimalField(decimal_places=2, max_digits=5)),
                ('fecha_asignacion', models.DateTimeField(auto_now_add=True)),
                ('heredero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones', to='users.heredero')),
                ('bien', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones', to='bienes.bien')),
            ],
        ),
    ]
