# Generated by Django 6.1 on 2026-08-26 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Billetera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saldo', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
            ],
        ),
        migrations.CreateModel(
            name='Transaccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=14)),
                ('tipo', models.CharField(choices=[('DEPOSITO', 'Deposito'), ('TRANSFERENCIA', 'Transferencia'), ('HERENCIA', 'Herencia')], default='TRANSFERENCIA', max_length=14)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
